import type { EventLogEntry } from "./app-events.ts";
import type {
  CandidatesPreviewItem,
  CompactionStatus,
  ToolRenderItem,
  ToolRenderPayload,
} from "./app-tool-stream.ts";
import type { DevicePairingList } from "./controllers/devices.ts";
import type { ExecApprovalRequest } from "./controllers/exec-approval.ts";
import type { ExecApprovalsFile, ExecApprovalsSnapshot } from "./controllers/exec-approvals.ts";
import type { SkillMessage } from "./controllers/skills.ts";
import type { GatewayBrowserClient, GatewayHelloOk } from "./gateway.ts";
import type { Tab } from "./navigation.ts";
import type { UiSettings } from "./storage.ts";
import type { ThemeTransitionContext } from "./theme-transition.ts";
import type { ThemeMode } from "./theme.ts";
import type {
  AgentsListResult,
  AgentsFilesListResult,
  AgentIdentityResult,
  AgentInfo,
  ChannelsStatusSnapshot,
  ConfigSnapshot,
  ConfigUiHints,
  CronJob,
  CronRunLogEntry,
  CronStatus,
  HealthSnapshot,
  LogEntry,
  LogLevel,
  NostrProfile,
  PresenceEntry,
  QuotationDraftDetail,
  QuotationDraftListItem,
  SessionsUsageResult,
  CostUsageSummary,
  SessionUsageTimeSeries,
  SessionsListResult,
  SkillStatusReport,
  StatusSummary,
} from "./types.ts";
import type { ChatAttachment, ChatQueueItem, ChatUploadedFile, CronFormState } from "./ui-types.ts";
import type { NostrProfileFormState } from "./views/channels.nostr-profile-form.ts";
import type { SessionLogEntry } from "./views/usage.ts";

export type AppViewState = {
  settings: UiSettings;
  password: string;
  tab: Tab;
  onboarding: boolean;
  basePath: string;
  connected: boolean;
  theme: ThemeMode;
  themeResolved: "light" | "dark";
  hello: GatewayHelloOk | null;
  lastError: string | null;
  eventLog: EventLogEntry[];
  assistantName: string;
  assistantAvatar: string | null;
  assistantAgentId: string | null;
  sessionKey: string;
  chatLoading: boolean;
  chatSending: boolean;
  chatMessage: string;
  chatAttachments: ChatAttachment[];
  chatUploadedFile: ChatUploadedFile | null;
  chatComposeDragOver: boolean;
  chatMessages: unknown[];
  chatToolMessages: unknown[];
  chatStream: string | null;
  chatStreamStartedAt: number | null;
  chatRunId: string | null;
  compactionStatus: CompactionStatus | null;
  toolRenderData: ToolRenderPayload | null;
  toolRenderSeq: number | null;
  toolRenderItems: ToolRenderItem[];
  candidatePreviews: CandidatesPreviewItem[];
  chatAvatarUrl: string | null;
  chatThinkingLevel: string | null;
  chatQueue: ChatQueueItem[];
  chatManualRefreshInFlight: boolean;
  nodesLoading: boolean;
  nodes: Array<Record<string, unknown>>;
  chatNewMessagesBelow: boolean;
  sidebarOpen: boolean;
  sidebarContent: string | null;
  sidebarError: string | null;
  splitRatio: number;
  scrollToBottom: (opts?: { smooth?: boolean }) => void;
  devicesLoading: boolean;
  devicesError: string | null;
  devicesList: DevicePairingList | null;
  execApprovalsLoading: boolean;
  execApprovalsSaving: boolean;
  execApprovalsDirty: boolean;
  execApprovalsSnapshot: ExecApprovalsSnapshot | null;
  execApprovalsForm: ExecApprovalsFile | null;
  execApprovalsSelectedAgent: string | null;
  execApprovalsTarget: "gateway" | "node";
  execApprovalsTargetNodeId: string | null;
  execApprovalQueue: ExecApprovalRequest[];
  execApprovalBusy: boolean;
  execApprovalError: string | null;
  pendingGatewayUrl: string | null;
  configLoading: boolean;
  configRaw: string;
  configRawOriginal: string;
  configValid: boolean | null;
  configIssues: unknown[];
  configSaving: boolean;
  configApplying: boolean;
  updateRunning: boolean;
  applySessionKey: string;
  configSnapshot: ConfigSnapshot | null;
  configSchema: unknown;
  configSchemaVersion: string | null;
  configSchemaLoading: boolean;
  configUiHints: ConfigUiHints;
  configForm: Record<string, unknown> | null;
  configFormOriginal: Record<string, unknown> | null;
  configFormMode: "form" | "raw";
  configSearchQuery: string;
  configActiveSection: string | null;
  configActiveSubsection: string | null;
  channelsLoading: boolean;
  channelsSnapshot: ChannelsStatusSnapshot | null;
  channelsError: string | null;
  channelsLastSuccess: number | null;
  bkContent: string;
  bkLoading: boolean;
  bkError: string | null;
  bkSaving: boolean;
  bkLastSuccess: number | null;
  bkDependentFiles: { mapping_table: string; price_library: string } | null;
  whatsappLoginMessage: string | null;
  whatsappLoginQrDataUrl: string | null;
  whatsappLoginConnected: boolean | null;
  whatsappBusy: boolean;
  nostrProfileFormState: NostrProfileFormState | null;
  nostrProfileAccountId: string | null;
  configFormDirty: boolean;
  presenceLoading: boolean;
  presenceEntries: PresenceEntry[];
  presenceError: string | null;
  presenceStatus: string | null;
  oosLoading: boolean;
  oosError: string | null;
  oosStats: import("./types.js").OosStats | null;
  oosList: import("./types.js").OosRecord[];
  oosByFile: import("./types.js").OosByFileRow[];
  oosByTime: import("./types.js").OosByTimeRow[];
  oosShowAddForm: boolean;
  /** 无货/缺货库：postgres | sqlite（从 /api/oos/stats 的 db 字段） */
  oosDb: "postgres" | "sqlite" | null;
  shortageLoading: boolean;
  shortageError: string | null;
  shortageStats: import("./types.js").ShortageStats | null;
  shortageList: import("./types.js").ShortageRecord[];
  shortageByFile: import("./types.js").ShortageByFileRow[];
  shortageByTime: import("./types.js").ShortageByTimeRow[];
  shortageShowAddForm: boolean;
  /** 缺货库：postgres | sqlite（从 /api/shortage/stats 的 db 字段） */
  shortageDb: "postgres" | "sqlite" | null;
  overviewOosStats: import("./types.js").OosStats | null;
  overviewOosError: string | null;
  overviewShortageStats: import("./types.js").ShortageStats | null;
  overviewShortageError: string | null;
  dashboardLoading: boolean;
  dashboardError: string | null;
  quotationStats: import("./types.js").QuotationDraftStats | null;
  dashboardOosByTime: import("./types.js").OosByTimeRow[];
  dashboardShortageByTime: import("./types.js").ShortageByTimeRow[];
  agentsLoading: boolean;
  agentsList: AgentsListResult | null;
  agentsError: string | null;
  agentsSelectedId: string | null;
  agentsPanel: "overview" | "tools";
  agentInfo: AgentInfo | null;
  agentInfoLoading: boolean;
  agentInfoError: string | null;
  agentFilesLoading: boolean;
  agentFilesError: string | null;
  agentFilesList: AgentsFilesListResult | null;
  agentFileContents: Record<string, string>;
  agentFileDrafts: Record<string, string>;
  agentFileActive: string | null;
  agentFileSaving: boolean;
  agentIdentityLoading: boolean;
  agentIdentityError: string | null;
  agentIdentityById: Record<string, AgentIdentityResult>;
  agentSkillsLoading: boolean;
  agentSkillsError: string | null;
  agentSkillsReport: SkillStatusReport | null;
  agentSkillsAgentId: string | null;
  sessionsLoading: boolean;
  sessionsResult: SessionsListResult | null;
  sessionsError: string | null;
  sessionsFilterActive: string;
  sessionsFilterLimit: string;
  sessionsIncludeGlobal: boolean;
  sessionsIncludeUnknown: boolean;
  usageLoading: boolean;
  usageRequestSeq: number;
  usageTimeSeriesRequestSeq: number;
  usageSessionLogsRequestSeq: number;
  usageResult: SessionsUsageResult | null;
  usageCostSummary: CostUsageSummary | null;
  usageError: string | null;
  usageStartDate: string;
  usageEndDate: string;
  usageSelectedSessions: string[];
  usageSelectedDays: string[];
  usageSelectedHours: number[];
  usageChartMode: "tokens" | "cost";
  usageDailyChartMode: "total" | "by-type";
  usageTimeSeriesMode: "cumulative" | "per-turn";
  usageTimeSeriesBreakdownMode: "total" | "by-type";
  usageTimeSeries: SessionUsageTimeSeries | null;
  usageTimeSeriesLoading: boolean;
  usageTimeSeriesCursorStart: number | null;
  usageTimeSeriesCursorEnd: number | null;
  usageSessionLogs: SessionLogEntry[] | null;
  usageSessionLogsLoading: boolean;
  usageSessionLogsExpanded: boolean;
  usageQuery: string;
  usageQueryDraft: string;
  usageQueryDebounceTimer: number | null;
  usageSessionSort: "tokens" | "cost" | "recent" | "messages" | "errors";
  usageSessionSortDir: "asc" | "desc";
  usageRecentSessions: string[];
  usageTimeZone: "local" | "utc";
  usageContextExpanded: boolean;
  usageHeaderPinned: boolean;
  usageSessionsTab: "all" | "recent";
  usageVisibleColumns: string[];
  usageLogFilterRoles: import("./views/usage.js").SessionLogRole[];
  usageLogFilterTools: string[];
  usageLogFilterHasTools: boolean;
  usageLogFilterQuery: string;
  workFilePaths: string[];
  workOriginalFileNamesByPath: Record<string, string>;
  workRunning: boolean;
  /** 0=识别表 1=查价格与库存 2=填表，执行中循环 */
  workProgressStage: number;
  workRunStatus: import("./controllers/work.js").WorkRunStatus;
  workRunId: string | null;
  workPendingChoices: import("./controllers/work.js").WorkPendingChoice[];
  workSelections: Record<string, string>;
  workResult: { success?: boolean; answer?: string; trace?: unknown[]; error?: string } | null;
  workError: string | null;
  workCustomerLevel: string;
  workDoRegisterOos: boolean;
  workPendingQuotationDraft: import("./controllers/work.js").PendingQuotationDraft | null;
  workQuotationDraftSaveStatus: import("./controllers/work.js").WorkQuotationDraftSaveStatus | null;
  workTextInput: string;
  workTextGenerating: boolean;
  workTextError: string | null;
  workPriceLevelOptions: Array<{ value: string; label: string }>;
  cronLoading: boolean;
  cronJobs: CronJob[];
  cronStatus: CronStatus | null;
  cronError: string | null;
  cronForm: CronFormState;
  cronRunsJobId: string | null;
  cronRuns: CronRunLogEntry[];
  cronBusy: boolean;
  fulfillDraftsLoading: boolean;
  fulfillDraftsError: string | null;
  fulfillDrafts: QuotationDraftListItem[];
  fulfillDetail: QuotationDraftDetail | null;
  fulfillDetailId: number | null;
  fulfillConfirmBusy: boolean;
  fulfillConfirmResult: { order_id?: string; message?: string } | null;
  fulfillFilterQuery: string;
  fulfillSortBy: "created_at" | "draft_no" | "name";
  fulfillSortDir: "asc" | "desc";
  fulfillPage: number;
  fulfillPageSize: number;
  procurementLoading: boolean;
  procurementError: string | null;
  procurementSuggestions: import("./types.js").ShortageRecord[];
  procurementSelectedKeys: string[];
  procurementApprovedKeys: string[];
  procurementApproveBusy: boolean;
  procurementApproveResult: { approved_count?: number; message?: string } | null;
  procurementFilterQuery: string;
  procurementSortBy: "uploaded_at" | "shortfall" | "count" | "product_name";
  procurementSortDir: "asc" | "desc";
  procurementPage: number;
  procurementPageSize: number;
  loadProcurementSuggestions: () => Promise<void>;
  replenishmentDrafts: import("./types.js").ReplenishmentDraftListItem[];
  replenishmentDetail: import("./types.js").ReplenishmentDraftDetail | null;
  replenishmentDetailId: number | null;
  replenishmentLoading: boolean;
  replenishmentError: string | null;
  replenishmentConfirmBusy: boolean;
  replenishmentConfirmResult: { executed?: number; message?: string } | null;
  replenishmentInputLines: import("./controllers/procurement.js").ReplenishmentInputLine[];
  replenishmentCreateBusy: boolean;
  loadProcurementReplenishment: () => Promise<void>;
  loadProcurementReplenishmentDetail: (draftId: number) => Promise<void>;
  confirmProcurementReplenishment: (draftId: number) => Promise<void>;
  deleteProcurementReplenishmentDraft: (draftId: number) => Promise<void>;
  onReplenishmentLineChange: (index: number, field: "product_or_code" | "quantity", value: string | number) => void;
  onReplenishmentAddLine: () => void;
  onReplenishmentRemoveLine: (index: number) => void;
  createProcurementReplenishmentDraft: () => Promise<void>;
  skillsLoading: boolean;
  skillsReport: SkillStatusReport | null;
  skillsError: string | null;
  skillsFilter: string;
  skillEdits: Record<string, string>;
  skillMessages: Record<string, SkillMessage>;
  skillsBusyKey: string | null;
  reportsLoading: boolean;
  reportsError: string | null;
  reportsTasks: import("./types.js").ReportTask[];
  reportsRecords: import("./types.js").ReportRecord[];
  reportsAdminToken: string;
  reportsEditingTaskId: string | null;
  reportsEditForm: import("./types.js").ReportTaskConfig;
  reportDetail: import("./types.js").ReportRecord | null;
  reportDetailLoading: boolean;
  selectedRecordId: number | null;
  reportsCopyJustDone: boolean;
  reportsDetailTab: "data" | "analysis";
  debugLoading: boolean;
  debugStatus: StatusSummary | null;
  debugHealth: HealthSnapshot | null;
  debugModels: unknown[];
  debugHeartbeat: unknown;
  debugCallMethod: string;
  debugCallParams: string;
  debugCallResult: string | null;
  debugCallError: string | null;
  logsLoading: boolean;
  logsError: string | null;
  logsFile: string | null;
  logsEntries: LogEntry[];
  logsFilterText: string;
  logsLevelFilters: Record<LogLevel, boolean>;
  logsAutoFollow: boolean;
  logsTruncated: boolean;
  logsCursor: number | null;
  logsLastFetchAt: number | null;
  logsLimit: number;
  logsMaxBytes: number;
  logsAtBottom: boolean;
  /** 万鼎价格库 / 产品映射表管理（/admin-data） */
  adminData: import("./controllers/admin-data.types.ts").AdminDataState;
  client: GatewayBrowserClient | null;
  refreshSessionsAfterChat: Set<string>;
  connect: () => void;
  setTab: (tab: Tab) => void;
  setTheme: (theme: ThemeMode, context?: ThemeTransitionContext) => void;
  applySettings: (next: UiSettings) => void;
  loadOverview: () => Promise<void>;
  loadAssistantIdentity: () => Promise<void>;
  loadCron: () => Promise<void>;
  loadFulfillDrafts: () => Promise<void>;
  handleWhatsAppStart: (force: boolean) => Promise<void>;
  handleWhatsAppWait: () => Promise<void>;
  handleWhatsAppLogout: () => Promise<void>;
  handleChannelConfigSave: () => Promise<void>;
  handleChannelConfigReload: () => Promise<void>;
  handleNostrProfileEdit: (accountId: string, profile: NostrProfile | null) => void;
  handleNostrProfileCancel: () => void;
  handleNostrProfileFieldChange: (field: keyof NostrProfile, value: string) => void;
  handleNostrProfileSave: () => Promise<void>;
  handleNostrProfileImport: () => Promise<void>;
  handleNostrProfileToggleAdvanced: () => void;
  handleExecApprovalDecision: (decision: "allow-once" | "allow-always" | "deny") => Promise<void>;
  handleGatewayUrlConfirm: () => void;
  handleGatewayUrlCancel: () => void;
  handleConfigLoad: () => Promise<void>;
  handleConfigSave: () => Promise<void>;
  handleConfigApply: () => Promise<void>;
  handleConfigFormUpdate: (path: string, value: unknown) => void;
  handleConfigFormModeChange: (mode: "form" | "raw") => void;
  handleConfigRawChange: (raw: string) => void;
  handleInstallSkill: (key: string) => Promise<void>;
  handleUpdateSkill: (key: string) => Promise<void>;
  handleToggleSkillEnabled: (key: string, enabled: boolean) => Promise<void>;
  handleUpdateSkillEdit: (key: string, value: string) => void;
  handleSaveSkillApiKey: (key: string, apiKey: string) => Promise<void>;
  handleCronToggle: (jobId: string, enabled: boolean) => Promise<void>;
  handleCronRun: (jobId: string) => Promise<void>;
  handleCronRemove: (jobId: string) => Promise<void>;
  handleCronAdd: () => Promise<void>;
  handleCronRunsLoad: (jobId: string) => Promise<void>;
  handleCronFormUpdate: (path: string, value: unknown) => void;
  handleSessionsLoad: () => Promise<void>;
  handleSessionsPatch: (key: string, patch: unknown) => Promise<void>;
  handleLoadNodes: () => Promise<void>;
  handleLoadPresence: () => Promise<void>;
  handleLoadSkills: () => Promise<void>;
  handleLoadDebug: () => Promise<void>;
  handleLoadLogs: () => Promise<void>;
  handleDebugCall: () => Promise<void>;
  handleRunUpdate: () => Promise<void>;
  setPassword: (next: string) => void;
  setSessionKey: (next: string) => void;
  setChatMessage: (next: string) => void;
  handleSendChat: (messageOverride?: string, opts?: { restoreDraft?: boolean }) => Promise<void>;
  handleAbortChat: () => Promise<void>;
  handleUploadChatFile: (file: File) => Promise<void>;
  clearChatUploadedFile: () => void;
  setChatComposeDragOver: (over: boolean) => void;
  handleComposeDrop: (file: File) => Promise<void>;
  removeQueuedMessage: (id: string) => void;
  handleChatScroll: (event: Event) => void;
  resetToolStream: () => void;
  resetChatScroll: () => void;
  exportLogs: (lines: string[], label: string) => void;
  handleLogsScroll: (event: Event) => void;
  handleOpenSidebar: (content: string) => void;
  handleCloseSidebar: () => void;
  handleSplitRatioChange: (ratio: number) => void;
};
